### PR TITLE
Add link to OCI specs latest webpage

### PR DESCRIPTION
**Pull request by jdolitsky**
A follow up to @sajayantony 's comment here: https://groups.google.com/a/opencontainers.org/g/dev/c/JELU5Gqsu2I/m/p5GiLRsSBgAJ

### CODE REVIEW

**Review by vsoch — APPROVED** [review]
Looks great!

**Comment by vsoch** [comment]
I'm good to merge, but we can wait for one more set of eyes in case I'm missing something.

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by vsoch** [comment]
Thanks @mikebrow !

**Pull request merged**
